{{- if .Values.nginxConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxConfig.name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    user nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      keepalive_timeout  65;

      server {
        listen       80;
        server_name  _;

        root   /usr/share/nginx/html;
        index  index.html;

        location / {
          try_files $uri $uri/ /index.html;
        }

        location ~* \.(jpg|jpeg|gif|png|css|js|ico|svg|woff|woff2|ttf|eot|webp)$ {
          expires max;
          log_not_found off;
          add_header Cache-Control "public, immutable";
        }

        location = /health/live {
          access_log off;
          return 200 'OK';
          add_header Content-Type text/plain;
        }

        location = /health/ready {
          access_log off;
          return 200 'OK';
          add_header Content-Type text/plain;
        }
      }
    }
{{- end }}
